name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
 job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            vcpkgCommitId: '5568f110b509a9fd90711978a7cb76bae75bb092'
          - os: ubuntu-latest
            vcpkgCommitId: '5568f110b509a9fd90711978a7cb76bae75bb092'
          - os: macos-latest
            vcpkgCommitId: '5568f110b509a9fd90711978a7cb76bae75bb092'
  
    steps:
    - uses: actions/checkout@v2
    
    - uses: humbletim/setup-vulkan-sdk@v1.0.3   
    - uses: lukka/run-vcpkg@v10
      id: runvcpkg
      with:
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgGitCommitId: '${{ matrix.vcpkgCommitId}}'

        
    - name: install sdl2
      run: vcpkg install sdl2[vulkan]
    - name: install sdl2_mixer
      run: vcpkg install sdl2-mixer
    - name: install freetype
      run: vcpkg install freetype
    - name: install spdlog
      run: vcpkg install spdlog
    - name: install vulkan
      run: vcpkg install vulkan
    - name: install vulkan_mem_allocator
      run: vcpkg install vulkan-memory-allocator
    - name: install stb
      run: vcpkg install stb
    - name: install glm
      run: vcpkg install glm
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S . -DCMAKE_TOOLCHAIN_FILE= ${{ runner.workspace }}/b/vcpkg/scripts/buildsystems/vcpkg.cmake

    #- name: Build
      # Build your program with the given configuration
      #run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    #- name: Test
     # working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      #run: ctest -C ${{env.BUILD_TYPE}}
      
