name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            vcpkgCommitId: '5568f110b509a9fd90711978a7cb76bae75bb092'
    steps:
    - uses: actions/checkout@v2
    
    - uses: humbletim/setup-vulkan-sdk@v1.0.3   
    - name: cd to vcpkg location
      run: cd .${{ runner.workspace }}/b/
    - name: get vcpkg
      run: git clone https://github.com/Microsoft/vcpkg.git
    - name: bootstrapvcpkg
      run: .${{ runner.workspace }}/b/vcpkg/bootstrap-vcpkg.bat
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -S . -DCMAKE_TOOLCHAIN_FILE= '${{ runner.workspace }}/b/vcpkg/scripts/buildsystems/vcpkg.cmake'
   
       
   #- name: Build
      # Build your program with the given configuration
      #run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    #- name: Test
     # working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      #run: ctest -C ${{env.BUILD_TYPE}}
      
