name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            vcpkgCommitId: '5568f110b509a9fd90711978a7cb76bae75bb092'
    steps:
    - uses: actions/checkout@v2
    
    - uses: humbletim/setup-vulkan-sdk@v1.0.3   
    - name: reps
      run : sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
  
    
    
    - name: update
      run: sudo apt-get update -y -qq
      
    - name : install sdl2
      run: sudo apt-get install libsdl2-dev
    - name: install sdl2-mixer
      run: sudo apt-get install libsdl2-mixer-dev
    - name: install clang
      run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
      
    - uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: '5568f110b509a9fd90711978a7cb76bae75bb092'
    - name: build
      uses: lukka/run-cmake@v10
      with:
          C: clang
          CXX: clang++
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: 'ninja-multi-vcpkg'

